### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jngeigight** [microsoft/openjdk#104]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by jngeigight** [comment]
Completely ignored arguments: [--ignoreme net.minecraft.client.main.Main]
[18:22:00] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:22:02] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:112) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar:?]
	at dvp.a(SourceFile:670) [1.17.1.jar:?]
	at dvp.<init>(SourceFile:429) [1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:179) [1.17.1.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:77) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
	... 5 more
[18:22:02] [Render thread/INFO]: Setting user: probro
[18:22:03] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe2d6c3760, pid=7604, tid=2156
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffe2d6c3760
[error occurred during error reporting (printing problematic frame), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe2d6c3f10]

# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\rosef\AppData\Roaming\.minecraft\hs_err_pid7604.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by brstaffoMS** [comment]
Hi @jngeigight! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
