### ISSUE TITLE
using Microsoft JDK can error due to a missing Packages directory

### ISSUE THREAD

**Issue by SingingBush** [microsoft/openjdk#339]
I've had some users of [Intellij D Language plugin](https://github.com/intellij-dlanguage/intellij-dlanguage) report [problems when using the Microsoft JDK](https://github.com/intellij-dlanguage/intellij-dlanguage/issues/652). The project is built using Gradle and when doing the gradle build the resulting error is output:

```
/home/********/.sdkman/candidates/java/11.0.13-ms/Packages does not exist.
```

Adding a directory named *Packages* to the root of the ms JDK solves the problem: https://github.com/intellij-dlanguage/intellij-dlanguage/issues/652#issuecomment-1312112121

I'm submitting here as there really shouldn't be a need for users to add a directory to their jdk and this 'Packages' directory is non-standard.

**Comment by karianna** [comment]
@SingingBush That looks like an SDKMan packaging issue to me, I think you'll need to report it there.

**Comment by SingingBush** [comment]
The linked comment had the path `C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot\Packages` which isn't sdkman.

**Comment by karianna** [comment]
@SingingBush That directory doesn't come from the Microsoft MSI installer so I think it's SDKMan that's adding it.

**Comment by aaronjyoder** [comment]
This issue has caused me to switch away from the Microsoft distribution of OpenJDK. This is only an issue on the Microsoft distribution of the JDK, and it's unclear to me why it would be any different than any other vendor in this case.

Marking this issue as invalid feels unproductive to me when you are the only vendor who has this issue.

**Comment by karianna** [comment]
@aaronjyoder That folder structure doesn't come from our installers so I can only conclude that it's being added in error somehow via SDKman. Have you reported the issue there?

**Comment by SingingBush** [comment]
That's actually the point of my initial report, that the folder is not created by the installer. The point is that for some reason the Microsoft JDK expects it be there.

Adding it manually fixes the problem. So Microsoft either need to ensure the directory is created during installation or change the code that expects it to already exist and just create it when needed.

**Comment by SingingBush** [comment]
I wonder if it's something to do with this https://github.com/microsoft/openjdk-jdk11u/blob/659a4669208645420e151e78ab5fd3ac3808b310/src/java.base/share/classes/jdk/internal/jrtfs/ExplodedImage.java#L57

The javadoc mention that the modules folder will be under _JAVA_HOME_ so presumably it expects the same for packages.

**Comment by SingingBush** [comment]
I just tested this locally on Fedora with a fresh download of the jdk-21.0.7 tarball. clone the repo of the intellij-dlanguage project and run `./gradlew runIde` using the microsoft JDK:

```
JAVA_HOME=/opt/microsoft-jdk-21.0.7 ./gradlew runIde
```

resulted in `Caused by: : /opt/microsoft-jdk-21.0.7/Packages does not exist.`

Here's some of the stack trace:

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':debugger:instrumentCode'.
> /opt/microsoft-jdk-21.0.7/Packages does not exist.

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':debugger:instrumentCode'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: : /opt/microsoft-jdk-21.0.7/Packages does not exist.
```

I tried to recreate the issue with a smaller Gradle project but couldn't. I suspect the [intellij-platform-gradle-plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin) is doing something with Gradle that surfaces this problem in the MS JDK that isn't present in other JDK's such as OpenJDK.

**Comment by brunoborges** [comment]
@SingingBush could you please test with the latest release?

**Comment by SingingBush** [comment]
My project now requires JDK 21 so I downloaded https://aka.ms/download-jdk/microsoft-jdk-21.0.9-linux-x64.tar.gz and used it to run the gradle wrapper in my project (latest commit in develop):

```
JAVA_HOME=~/dev/tools/microsoft-jdk-21.0.9-linux-x64/jdk-21.0.9+10 ./gradlew runIde
```
(this project also requires the dmd compiler to be installed)

I see the same problem:

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':utils:instrumentCode'.
> /home/******/dev/tools/microsoft-jdk-21.0.9-linux-x64/jdk-21.0.9+10/Packages does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to generate a Build Scan (Powered by Develocity).
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':debugger:instrumentCode'.
> /home/******/dev/tools/microsoft-jdk-21.0.9-linux-x64/jdk-21.0.9+10/Packages does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to generate a Build Scan (Powered by Develocity).
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 1s
41 actionable tasks: 24 executed, 17 from cache
Configuration cache entry reused.
```

**Comment by brianjstafford** [comment]
Hey @SingingBush - I'll have someone try to reproduce and investigate the issue this sprint.

**Comment by jmjaffe37** [comment]
@SingingBush, @aaronjyoder, thank you for your patience on this issue! We have had a lot on our plates/backlog lately.

It turns out that the issue is actually due to some hardcoded lines of source code within the `Apache Ant`. This issue is still present in the most recent version `1.10.17`, but I have propose a code change which will fix this in all future versions: https://github.com/apache/ant/pull/230

If you are curious, here are the exact problem lines within ant's source code:

File (github link): [`src/main/org/apache/tools/ant/types/Path.java`](https://github.com/apache/ant/blob/ead2a75806f3cef76601b965bdfad0ca0f93e55a/src/main/org/apache/tools/ant/types/Path.java#L611-L618)

Code snippets in question:
```
    /**
     * Add the Java Runtime classes to this Path instance.
     */
    public void addJavaRuntime() {

        ... <skipping irrelevant code> ...

        if (System.getProperty("java.vendor").toLowerCase(Locale.ENGLISH).contains("microsoft")) {
            // TODO is this code still necessary? is there any 1.2+ port?
            // Pull in *.zip from packages directory
            FileSet msZipFiles = new FileSet();
            msZipFiles.setDir(new File(JavaEnvUtils.getJavaHome()
                    + File.separator + "Packages"));
            msZipFiles.setIncludes("*.ZIP");
            addFileset(msZipFiles);
        }
```

**Note**: there exists an old `TODO` here which shows that even the Ant devs have been skeptical of this code for a while now.

The above code ends with the function call `addFileset(msZipFiles);` which is defined as follows:
```
    /**
     * Adds a nested <code>&lt;fileset&gt;</code> element.
     * @param fs a <code>FileSet</code> to be added to the path
     * @throws BuildException on error
     */
    public void addFileset(FileSet fs) throws BuildException {
        if (fs.getProject() == null) {
            fs.setProject(getProject());
        }
        add(fs);
    }
```

Please let me know if you have any questions :)

CC: @karianna, @brianjstafford, @brunoborges

**Comment by brunoborges** [comment]
It's been several months. Closing this issue now.

**Comment by jmjaffe37** [comment]
@brunoborges, this issue is still open for the following reason: even though the bugfix is in place in the ant repo, the fix will only be available to customers once ant 1.0.18 comes out. I can ping them again to ask if they are willing to release soon (they previously told me that they would do a release around July).

**Comment by brunoborges** [comment]
@jmjaffe37 is there a workaround for our JDK? Do we really depend on Apache Ant fix before we can fix our own package?

**Comment by jmjaffe37** [comment]
@brunoborges, there is no workaround that we (Microsoft) can implement because this is due to a hardcoded bug in Ant's code. See the PR linked below for more info
Note: the only actual workaround is the one documented above which is on the customer side -- the customer needs to create an empty `packages` directory in `$JAVA_HOME` if they are using Microsoft's Build of the OpenJDK with Ant

Link: https://github.com/apache/ant/pull/230/changes

**Comment by aaronjyoder** [comment]
I haven't kept up with this issue as much as I should have, but I really appreciate you guys looking into it and figuring out the issue!

**Comment by brunoborges** [comment]
@jmjaffe37 if this problem only happens on our JDK and not on Temurin or Zulu or any other JDK, then it is a bug on our side.

I actually agree with the Apache Ant change. The build tool should have a JDK vendor specific fix.

**Comment by jmjaffe37** [comment]
@brunoborges, please see the pull request linked below. I have already fixed this issue with that linked PR for ant in that was merged in April. We are just waiting for them to release the next version of ant. They are a little behind schedule (they told me it would be out in June), so we only have the following options:

1) Ask/remind the Ant folks to publish the next version (I have been asking about once a month).
2) We can ship an empty "Packages" folder on every new JDK we make (this technically avoids the bug for ant, but it adds unnecessary folders for everyone. This folder was used in a system that is out of date by decades).
3) Publish our own temporary version of ant while we wait for the new ant to come out.

I personally would only stand behind option 1. Please let me know if you have any other ideas.

Link: https://github.com/apache/ant/pull/230/changes

**Comment by brunoborges** [comment]
Thanks @jmjaffe37 ... Option 3 is not gonna work. Option 2 is the way to go, while we wait for 1.
