### ISSUE TITLE
Minecraft keeps crashing on Windows 11, dont know why?

### ISSUE THREAD

**Issue by lSherozl** [microsoft/openjdk#590]
[hs_err_pid29216.log](https://github.com/microsoft/openjdk/files/14202596/hs_err_pid29216.log)

**Comment by lSherozl** [comment]
Part of the log before crash [16:07:42] [Render thread/INFO]: Cleared 175 unneeded book NBT tags
[16:07:43] [Thread-76/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar:6.0.3+6.0.3+master.039e4ea9]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:95) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.1.jar%23142!/:build 7]
[16:07:43] [Thread-76/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Buffer is unbound or is already unmapped.'
[16:07:43] [Render thread/INFO]: Stopping worker threads
[16:07:43] [Render thread/INFO]: Started 10 worker threads
[16:07:43] [Thread-78/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar:6.0.3+6.0.3+master.039e4ea9]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) [securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) [securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) [securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
[16:07:44] [Render thread/ERROR]: Founded directories but custom loading gif is missing
[16:07:46] [Render thread/WARN]: Time from main menu to in-game was 227.10898 seconds
[16:07:46] [Render thread/WARN]: Total time to load game and open world was 452.654 seconds
[16:07:47] [Server thread/INFO]: Saving and pausing game...
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/minecraft:overworld
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/minecraft:the_end
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/blue_skies:everdawn
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/minecraft:the_nether
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/blue_skies:everbright
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/undergarden:undergarden
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/twilightforest:twilight_forest
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/feywild:marketplace
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/l2library:maze
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/lostcities:lostcity
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/aether:the_aether
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/deeperdarker:otherside
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/atlantis:atlantis
[16:07:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newi]'/feywild:feywild
[16:07:48] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2133ms or 42 ticks behind
[16:07:51] [Render thread/INFO]: Exception when loading ecologics:prickly_pear texture, using material colour.
[16:07:51] [Render thread/INFO]: No texture minecraft:textures/missingno.png
[16:07:52] [Render thread/INFO]: Exception when loading everycomp:db/aether_redux/cloudcap_beam texture, using material colour.
[16:07:52] [Render thread/INFO]: No texture everycomp:textures/block/db/aether_redux/cloudcap_beam_side.png

**Comment by lSherozl** [comment]
![image](https://github.com/microsoft/openjdk/assets/65663746/dd922bf4-a414-4e03-831b-4024c9735af1)

**Comment by karianna** [comment]
You're using the Eclipse Temurin Binary, please file issues over at www.github.com/adoptium/adoptium-support

**Comment by lSherozl** [comment]
ill report there but was happening with JDK 17 as well
